import type { Metadata as NextMetadata } from 'next'
import Header from '@/component/Layout/Header/Header'
import Footer from '@/component/Layout/Footer/Footer'
import Providers from '@/redux/Provider'
import '@/styles/index.scss'

interface Metadata extends NextMetadata {
	image?: string
}

export const metadata: Metadata = {
	title: 'Aliexpress',
	description:
		'Generated by create next the best online store in Kyrgyzstan/Bishkek',
	image: './logo.svg',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body suppressHydrationWarning={true}>
				<Providers>
					<Hea der />
					<main>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
